---
title: Pixel Punch
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'In this 4th year of Pixel Punch, we will be challenging
              four brave designers do their best Captain Kirk and puzzle
              their way through galactic challenges guaranteed to test
              their creativity, fortitude and ability to think on their
              feet. We’re excited to bring together friends, new and old,
              to explore new solar systems together. We’ve got the starship,
              you bring your skills.'

baseurl:
url:
twitter_username: voxmedia
github_username: voxmedia
markdown: kramdown
gems:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- clock
- 2014
- 2015
- 2016
